language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache: npm

before_script:
  - BUILD_VERSION=$(cat package.json | grep version | head -1 | awk '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')

script:
  - npm run lint
  - npm run test

after_success:
  - docker build -t splitsoftware/split-evaluator:${BUILD_VERSION} -t splitsoftware/split-evaluator:latest .
