jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "lts/*"
      cache: npm
      script:
        - npm run lint
        - npm run test

    - stage: docker
      language: minimal
      services:
        - docker
      before_script:
        - BUILD_VERSION=$(cat package.json | grep version | head -1 | awk '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
      script:
        - docker build -t ${ARTIFACTORY_REGISTRY}/split-evaluator:${BUILD_VERSION} -t ${ARTIFACTORY_REGISTRY}/split-evaluator:latest .
      deploy:
        provider: script
        script:
          - echo "${ARTIFACTORY_PASSWORD}" | docker login -u "${ARTIFACTORY_USER}" --password-stdin "${ARTIFACTORY_REGISTRY}"
          - docker push ${ARTIFACTORY_REGISTRY}/split-evaluator
        skip_cleanup: true
        on:
          branch: INFRA-1540

stages:
  - name: test
  - name: docker
